//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Common.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NTS.Common.Resource.TextResource", typeof(TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại mã vạch.
        /// </summary>
        public static string BarcodeType {
            get {
                return ResourceManager.GetString("BarcodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhãn hiệu.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model xe.
        /// </summary>
        public static string BrandModel {
            get {
                return ResourceManager.GetString("BrandModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục con.
        /// </summary>
        public static string CategoryChild {
            get {
                return ResourceManager.GetString("CategoryChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại mã.
        /// </summary>
        public static string CodeType {
            get {
                return ResourceManager.GetString("CodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Màu sắc.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bình luận.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khóa học.
        /// </summary>
        public static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người liên hệ của khách hàng.
        /// </summary>
        public static string CustomerContact {
            get {
                return ResourceManager.GetString("CustomerContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày, đến ngày.
        /// </summary>
        public static string DateFromTo {
            get {
                return ResourceManager.GetString("DateFromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quận/Huyện.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên gia .
        /// </summary>
        public static string EmployeeSpecialist {
            get {
                return ResourceManager.GetString("EmployeeSpecialist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phản hồi.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm quyền.
        /// </summary>
        public static string GroupUser {
            get {
                return ResourceManager.GetString("GroupUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home link.
        /// </summary>
        public static string HomeLink {
            get {
                return ResourceManager.GetString("HomeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lời tựa.
        /// </summary>
        public static string HomeService {
            get {
                return ResourceManager.GetString("HomeService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silder bar home.
        /// </summary>
        public static string HomeSlider {
            get {
                return ResourceManager.GetString("HomeSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMND/CCCD.
        /// </summary>
        public static string IdentifyNum {
            get {
                return ResourceManager.GetString("IdentifyNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMND/CCCD hoặc email.
        /// </summary>
        public static string IdentifyNumAndEmail {
            get {
                return ResourceManager.GetString("IdentifyNumAndEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh.
        /// </summary>
        public static string ImagePath {
            get {
                return ResourceManager.GetString("ImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư.
        /// </summary>
        public static string Inbox {
            get {
                return ResourceManager.GetString("Inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng.
        /// </summary>
        public static string Learer {
            get {
                return ResourceManager.GetString("Learer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài giảng.
        /// </summary>
        public static string Lesson {
            get {
                return ResourceManager.GetString("Lesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài học của khóa học.
        /// </summary>
        public static string LessonCourse {
            get {
                return ResourceManager.GetString("LessonCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sở/Huyện.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản, mật khẩu.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị chủ quản.
        /// </summary>
        public static string ManageUnit {
            get {
                return ResourceManager.GetString("ManageUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng dẫn sử dụng.
        /// </summary>
        public static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng dẫn.
        /// </summary>
        public static string Manunal {
            get {
                return ResourceManager.GetString("Manunal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        public static string Notify {
            get {
                return ResourceManager.GetString("Notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP.
        /// </summary>
        public static string OTP {
            get {
                return ResourceManager.GetString("OTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường Link.
        /// </summary>
        public static string PageLink {
            get {
                return ResourceManager.GetString("PageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại bao bì.
        /// </summary>
        public static string ParkingType {
            get {
                return ResourceManager.GetString("ParkingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string PassWord {
            get {
                return ResourceManager.GetString("PassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        public static string PassWordNew {
            get {
                return ResourceManager.GetString("PassWordNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ.
        /// </summary>
        public static string PassWordOld {
            get {
                return ResourceManager.GetString("PassWordOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biển số xe.
        /// </summary>
        public static string PlateNumber {
            get {
                return ResourceManager.GetString("PlateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chương trình.
        /// </summary>
        public static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu hỏi.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trung tâm đăng kiểm.
        /// </summary>
        public static string RegisterCentral {
            get {
                return ResourceManager.GetString("RegisterCentral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng kiểm.
        /// </summary>
        public static string Registry {
            get {
                return ResourceManager.GetString("Registry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểm tra.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu chuẩn kiểm tra.
        /// </summary>
        public static string TestStandard {
            get {
                return ResourceManager.GetString("TestStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủ đề.
        /// </summary>
        public static string Topic {
            get {
                return ResourceManager.GetString("Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủ đề con.
        /// </summary>
        public static string TopicChild {
            get {
                return ResourceManager.GetString("TopicChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình thanh toán.
        /// </summary>
        public static string UserPayment {
            get {
                return ResourceManager.GetString("UserPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xe.
        /// </summary>
        public static string Vehicle {
            get {
                return ResourceManager.GetString("Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký xe.
        /// </summary>
        public static string Vehicles {
            get {
                return ResourceManager.GetString("Vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chia sẻ đăng ký xe.
        /// </summary>
        public static string VehiclesShare {
            get {
                return ResourceManager.GetString("VehiclesShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại xe.
        /// </summary>
        public static string VehicleType {
            get {
                return ResourceManager.GetString("VehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vi phạm.
        /// </summary>
        public static string VioLation {
            get {
                return ResourceManager.GetString("VioLation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo vi phạm.
        /// </summary>
        public static string ViolationReport {
            get {
                return ResourceManager.GetString("ViolationReport", resourceCulture);
            }
        }
    }
}
